apiVersion: v1
kind: Service
metadata:
  name: eventhub-management-service
spec:
  selector:
    app: eventhub-management-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort