apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -dev

patchesStrategicMerge:
  - ingress-patch.yaml

images:
  - name: alysongustavo/eventhub-management-service
    newName: alysongustavo/eventhub-management-service
    newTag: dev-latest

configMapGenerator:
  - name: eventhub-mgmt-config
    envs:
      - params.properties